title: "Eqivalon Pages"
email: 
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Eqivalon
paginate: 30
disqus: 'eqivalonpage'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: masukankodegoogleanalytic

# Authors
authors:
  eqivalon:
    name: Eqivalon
    display_name: Eqivalon
    avatar: 'assets/images/john.png'
    email: 
    web: https://eqivalon.github.io
    twitter: https://twitter.com
    description: "Owner of this pages"

# Social
social:
  instagram: https://www.instagram.com/eqivalon/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives